repos:
-   repo: https://github.com/adamchainz/django-upgrade
    rev: 1.20.0
    hooks:
    -   id: django-upgrade
        args: [--target-version, "4.2"]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]