# Generated by Django 5.2 on 2025-06-10 14:56

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('categories', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Handbooks and manuals by discipline'), ('2', 'Business books'), ('3', 'Books of literary criticism'), ('4', 'Books about literary theory'), ('5', 'Books about literature')], default=['1', '5'], max_length=9)),
                ('tags', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('sex', 'Sex'), ('work', 'Work'), ('happy', 'Happy'), ('food', 'Food'), ('field', 'Field'), ('boring', 'Boring'), ('interesting', 'Interesting'), ('huge', 'Huge'), ('nice', 'Nice')], max_length=54)),
                ('favorite_tags', multiselectfield.db.fields.SortMultiSelectField(blank=True, choices=[('sex', 'Sex'), ('work', 'Work'), ('happy', 'Happy'), ('food', 'Food'), ('field', 'Field'), ('boring', 'Boring'), ('interesting', 'Interesting'), ('huge', 'Huge'), ('nice', 'Nice')], max_length=54)),
                ('published_in', multiselectfield.db.fields.MultiSelectField(choices=[('Canada - Provinces', [('AB', 'Alberta'), ('BC', 'British Columbia')]), ('USA - States', [('AK', 'Alaska'), ('AL', 'Alabama'), ('AZ', 'Arizona')])], max_length=31, verbose_name='Province or State')),
                ('chapters', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Chapter I'), ('2', 'Chapter II'), ('3', 'Chapter III')], default=['1'], max_length=5)),
            ],
        ),
    ]
