# Generated by Django 3.0.5 on 2020-04-21 09:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tabs_with_other',
            field=multiselectfield.db.fields.MultiSelectWithOtherField(blank=True, choices=[('sex', 'Sex'), ('work', 'Work'), ('happy', 'Happy'), ('food', 'Food'), ('field', 'Field'), ('boring', 'Boring'), ('interesting', 'Interesting'), ('huge', 'Huge'), ('nice', 'Nice'), ('other', 'Other')], max_length=154, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_in',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Canada - Provinces', (('AB', 'Alberta'), ('BC', 'British Columbia'))), ('USA - States', (('AK', 'Alaska'), ('AL', 'Alabama'), ('AZ', 'Arizona')))], max_length=31, verbose_name='Province or State'),
        ),
    ]
